name: Mirror to GitLab

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Mirror to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git config --global user.email "mirror@github.com"
          git config --global user.name "GitHub Mirror Bot"
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/ThaboTheDev/AdventureGame.git
          git push --mirror gitlab
